version: '3'
services:
  redis-server:
    image: 'redis'
  node-app: # Build the image from the dockerfile in the current directory
    restart: always # Always restart the container if it crashes
    build: . 
    ports:
      - "4001:8081"